#import "Save.h"

//#define CF_DEBUG
#define CF_AUDIO

// END DEFAULTS

#define TOWERS_LIMIT 8

#define TURRET_COST 25
#define TURRET_DAMAGE_TO_SPIDER 13
#define TURRET_DAMAGE_TO_CATERPILLAR 4.15
#define TURRET_DAMAGE_TO_CHIP 5
#define TURRET_RANGE 1.8
#define TURRET_RATE 0.5

#define TANK_COST 25
#define TANK_DAMAGE_TO_SPIDER 16.666
#define TANK_DAMAGE_TO_CATERPILLAR 20
#define TANK_DAMAGE_TO_CHIP 5
#define TANK_RANGE 1.8
#define TANK_RATE 1.3

#define LASER_COST 25
#define LASER_DAMAGE_TO_SPIDER 5
#define LASER_DAMAGE_TO_CATERPILLAR 5
#define LASER_DAMAGE_TO_CHIP 50
#define LASER_RANGE 1.8
#define LASER_RATE 1.5

#define BOMB_COST 50
#define BOMB_RANGE 1.8

#define SPIDER_SPEED 1.4

#define CATERPILLAR_SPEED 1.0

#define CHIP_SPEED 3.0

#define MERGE_DAMAGE_IMPROVE 0.0
#define MERGE_RANGE_IMPROVE 0.0
#define MERGE_COST 0.5

#define WAVES 100

#define ENEMIES_NUMBER_INCREASE_PER_LEVEL 0.1
#define ENEMIES_RESISTANCE_INCREASE_PER_LEVEL 0

#define COMBO_TIME 1.5

#define SLOW_FACTOR 0.5
#define SLOW_TIME 3.0

// MISC...

#define FONT_SIZE 20
